### ISSUE TITLE
Moving Cars with random targets on map and navmesh pathffinding

### ISSUE THREAD

**Issue by koerners** [koerners/ogw_g8#12]

**Comment by asoehnen** [comment]
Cars can be made to drive only on streets the following way:
- Create a separate Empty with a NavMeshSurface component
- Make parts of the Plane_street prefab non-walkable (via NavMeshModifier component) 
- Include the NavMeshSurface in the GridController Script and call its `BuildNavMesh()` method after creation of the grid cells

**Comment by koerners** [comment]
Moved to backlog: For now, colliders are disabled
