### ISSUE TITLE
Implement Resource managment 

### ISSUE THREAD

**Issue by koerners** [koerners/ogw_g8#20]
Depending on the level of buildings, a certain level of resources is produced

**Comment by asoehnen** [comment]
Integrathe these resource Types:
- Food
- Minerals
- Living Space
- (City Health)
and define resource production and costs for each building level

**Comment by asoehnen** [comment]
[Spreadsheet for calculations](https://docs.google.com/spreadsheets/d/1Zm-72hbUbfDj5uYXX6dW111I8yzclVdGEsUu1xACiBQ/edit#gid=0)

**Comment by koerners** [comment]
> [Spreadsheet for calculations](https://docs.google.com/spreadsheets/d/1Zm-72hbUbfDj5uYXX6dW111I8yzclVdGEsUu1xACiBQ/edit#gid=0)

Häng Ma überall noch 1-2 Nuller dran dann wirkt das ein bisschen größer :D
