### ISSUE TITLE
Refine concrete values for resources

### ISSUE THREAD

**Issue by koerners** [koerners/ogw_g8#36]

**Comment by asoehnen** [comment]
[Calculation Sheet with Parameters](https://docs.google.com/spreadsheets/d/1Zm-72hbUbfDj5uYXX6dW111I8yzclVdGEsUu1xACiBQ/edit?usp=sharing)

**Comment by asoehnen** [comment]
added calculated resource costs to the game.
Further progress also depends on / related todos:
- remove refinery from the game (?)
- decide how stronger and more expensive unit types should be integrated into the game

**Comment by asoehnen** [comment]
Values should be in the right ballpark for an engaging experience. After some playtesting and with extensive knowlegde of the game I am able to reach wave 15 (for now the max?). 

I let a friend play, and as intended it seemed quite difficult for a first timer, but not hopeless. This was with an earlier version, will do this again
