### ISSUE TITLE
Background music

### ISSUE THREAD

**Issue by koerners** [koerners/ogw_g8#51]
Possibly changing when fighting

**Comment by asoehnen** [comment]
Maybe a background music is too distracting, but here are two ideas:

[EDM-Style](https://www.youtube.com/watch?v=Q-mGfuBrCMI), best for main menu only?
[Lofi Synthwave](https://www.youtube.com/watch?v=gnz2sqkrEfc) has rain sounds in the background

Will play some games with this running in the background and reporting back
