### ISSUE TITLE
Implement a Tutorial

### ISSUE THREAD

**Issue by koerners** [koerners/ogw_g8#55]
Link video from demo session and popup window on start

**Comment by koerners** [comment]
- [ ] Popup window on start explaning basic control scheme
- [ ] Rename "About" section to "Introduction" and link it in the popup as well

**Comment by asoehnen** [comment]
maybe a "?" button in top left that opens the popup menu also

**Comment by asoehnen** [comment]
One idea for the popup would be a simple overview containing:
- more detailed explanation of the top left buttons (and the three bottom right buttons)
- all shortcuts
- an explanation on how to move the camera around
- the goal of the game
I could create a simple png looking approximately like this (using the correct in-game style):
![sketch](https://user-images.githubusercontent.com/35302506/128615893-a2a9a608-b39a-4a4c-8059-cde6e6d9eb1b.png)
What do you think?

**Comment by asoehnen** [comment]
![Tutorial](https://user-images.githubusercontent.com/35302506/128648699-64b7afd9-1366-4fef-bbd2-a05116f7621c.png)
First Draft, any ideas?
@dongzi123 should I add a yellow border and "x" icon in the image? My idea was that this image will fill a popup that takes up approx 80% of screen area

**Comment by dongzi123** [comment]
i think it's perfect

**Comment by koerners** [comment]
Please check shortcuts (e.g.) R -> Rotate vehicle when building

**Comment by koerners** [comment]
Also important: Free looking around with right mouse pressed

**Comment by koerners** [comment]
> 
> 
> maybe a "?" button in top left that opens the popup menu also

This also definetly is required

**Comment by koerners** [comment]
press "alt" to show all units on the field

**Comment by asoehnen** [comment]
> Also important: Free looking around with right mouse pressed
Already there,
"RMB  Look around" (?)
there is not that much space, hence I tried to keep it as short as possible. Will think of other possibilities that are also short

**Comment by dongzi123** [comment]
maybe add a "how to play" button in start and pause menu? What do you think?

**Comment by asoehnen** [comment]
> maybe add a "how to play" button in start and pause menu? What do you think?

Yes, I think that fits better for an image than the"Tutorial" Button mentioned in #108 .
#108 also suggests moving the video to a separate button. If possible, that would be great, so:
"How to play" in both menus shows the image
"Introduction" in the main menu plays the video
What are your thoughts? I have much time and could also try to do some of this work.

**Comment by dongzi123** [comment]
Do we still need #107 if we implemented these both menus?

**Comment by asoehnen** [comment]
I think #107 is not necessary. One the one hand, a player would be forced to read the instructions, but on the other hand I would feel irritated by a popup that opens every game start.

**Comment by dongzi123** [comment]
> I think #107 is not necessary. One the one hand, a player would be forced to read the instructions, but on the other hand I would feel irritated by a popup that opens every game start.

I agree. Let's close it.
