### ISSUE TITLE
Implement Hotkeys

### ISSUE THREAD

**Issue by koerners** [koerners/ogw_g8#57]
- [x] play / pause with space
- [x] car with 1
- [x] halftruck with 2
- [x] truck with 3
- [x] tower with 4
- [x] B for Buildmenu
- [x] R for wall repair
- [x] #69 with Ctrl+G (?)
- [x] U for Build Units menu

**Comment by asoehnen** [comment]
god mode shortcut is implemented, using just the (old?) API in the Shortcuts.cs script.
For the god mode it does not matter, but a repeat delay is still needed if we continue with this approach.  There is a new input system package that might allow doing this nicely, but importing it seems to change quite a bit and I am afraid to break things.

**Comment by asoehnen** [comment]
R conflicted with reset camera, moved reset camera to Control+R
