### ISSUE TITLE
God mode

### ISSUE THREAD

**Issue by koerners** [koerners/ogw_g8#69]
Implement god mode (maybe with hotkey) to ease dev

-> no cost for anything etc.

**Comment by asoehnen** [comment]
Giving the player a large amount of resources (like a cheat code) could be easier to implement. Would this achieve all things a god mode does?

**Comment by koerners** [comment]
> 
> 
> Giving the player a large amount of resources (like a cheat code) could be easier to implement. Would this achieve all things a god mode does?

jap
