### ISSUE TITLE
Final Balancing

### ISSUE THREAD

**Issue by koerners** [koerners/ogw_g8#70]

**Comment by asoehnen** [comment]
From playtesting the last two days I agree that currently, the game is a little bit too easy. On saturday it felt harder :D
Propositions: 
- Lower the initial living space to force an upgrade of the living quarters early on
- make Buildings a little bit more expensive (on saturday I reduced overall building cost quite a bit)
- tune the buff, especially make the auto generated waves harder

**Comment by asoehnen** [comment]
also: make repairing the wall significantly more expensive

**Comment by asoehnen** [comment]
Just did a full playtest with someone playing for the second time, and especially after wave 10 seems to easy
