### ISSUE TITLE
Towers are not shooting

### ISSUE THREAD

**Issue by koerners** [koerners/ogw_g8#85]
Tower prefab is probably too high so it cant shoot

**Comment by asoehnen** [comment]
made towers only half as high as a quick test, but the issue seems to persist

**Comment by koerners** [comment]
Probably would need a up and down pivot

**Comment by asoehnen** [comment]
![grafik](https://user-images.githubusercontent.com/35302506/127666702-9ec20da8-b306-4159-a4af-3eb54d10b243.png)
Even with very low height tower does not shoot. How would a pivot be implemented? Suggest to review this next session

**Comment by koerners** [comment]
Or: Its a feature not a bug.
Wie wir gesehen haben schießen sie ja wenn der Winkel stimmt und iwie kann man das finde ich auch gut als "Buff" verkaufen dass Türme eben nicht übermächtig sind weil Gegner nur kurze Zeit beschießbar sind
