### ISSUE TITLE
Sound for upgrades and unit placements

### ISSUE THREAD

**Issue by asoehnen** [koerners/ogw_g8#89]

**Comment by asoehnen** [comment]
added two sounds (build.mp3 and place_unit.mp3) to the root asset directory. However, when added in the "Buy Sound" slot of the Unit Placement script, an ingame warning "Can not play a disabled audio source" comes up and nothing plays. Not sure why that is, tried some dirty hacks but to no avail :(

**Comment by koerners** [comment]
@asoehnen, logic for sound has been moved to 

- BuildUnitController
- UpgradeController

please see there for fine tuning and indicate if further help is needed

**Comment by asoehnen** [comment]
very nice! I just increased the volume a tiny bit
